name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # 1. Ejecutar Pruebas Automatizadas
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar Pruebas Unitarias
        run: node tests/sistema.test.js

  # 2. Despliegue Automático a GitHub Pages
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto (carpeta src)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'

      - name: Desplegar en la Nube
        id: deployment
        uses: actions/deploy-pages@v4